version: '3'

services:
  db:
    image: postgres
    container_name: spidy-db
    restart: always
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - "./database:/var/lib/postgresql/data"
      - "./initdb:/docker-entrypoint-initdb.d"
    ports:
      - "5432:5432"
    networks: 
      - net

  web:
    build: 
      context: .
    container_name: spidy-web
    ports:
      - "5000:5000"
    volumes:
      - ".:/usr/src/spidy/backend"
    tty: true
    environment:
      TZ: Asia/Tokyo
      FLASK_APP: run.py
      FLASK_ENV: development
    command: sh -c  "sh initdb/init.sh && flask run -h 0.0.0.0 --port 5000"
    depends_on: 
      - db
    networks: 
      - net

volumes:
  database:
networks: 
  net: