name: CI

on:
  pull_request:
    branches:
      - feature/*
  push:
    branches:
      - main
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build image
        run: docker-compose build --no-cache

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Test
        run: docker-compose run web pytest

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to heroku
        if: github.event.pull_request.merged == true
        run: echo "program deploy to heroku"
